### PR TITLE
Feature/stack character maps

### PR DESCRIPTION
**Pull request by loodakrawa**

### CODE REVIEW

**Comment by AndyGFX** [comment]
Hi, 
nice feature. 

After a few quick test I found this problems with new push/pop characterMaps:

- when is animation changed after characterMaps changes, transition has some-time wrong sprite scale and rotation when transition start (when is finished, then is scale correct)- looks like starting values are changed too to any values
- when I repeatly change characterMaps with transition to another animation, I got error for all pivots:
...
transform.localPosition assign attempt for 'Pivot 0' is not valid. Input localPosition is { NaN, NaN, 0.000000 }.
UnityEngine.Transform:set_localPosition(Vector3)
...
- popCharMap doesn't always return sprite back - after pop all maps from list, sprites are showed back in animation (maybe only example imlementation has issue)

Andy.

**Comment by loodakrawa** [comment]
Hi,
Are you experiencing these issues with one of the included .scmls or one of your own? I can't replicate any of the issues.

* Character maps should have zero effect on the actual transforms, they just replace one sprite with the other but should have the same transforms. Does the same happen when you transition without applying any CharMaps?

* PopCharMap is a void method and is not supposed to return anything. It just removes the top CharMaps and applies the one below or the default if the last was removed. What exactly to you mean by this?

**Comment by AndyGFX** [comment]
Hi, 
thx for answer, now it's more clean for me how maps works. 

Note: Attached link is animation (modified spriter animation) where I found described issue with transition.

Andy.

https://drive.google.com/open?id=0B_uExaroZMURdjYzTGVEeWF3N0U

**Comment by loodakrawa** [comment]
The attached file is corrupted - I've tried a couple of times but I can't open the .zip file. Can you upload it again?

**Comment by AndyGFX** [comment]
I send file to your @. Give me second.

Andy.

**Comment by loodakrawa** [comment]
The issue you're experiencing has nothing to do with CharacterMaps but with the fact you have a different hierarchy in different animations. In order to have transitions (or animation blending) the hierarchies must be identical.

https://github.com/loodakrawa/SpriterDotNet/#animation-blending

**Comment by AndyGFX** [comment]
Hi,

thanks and sorry for bug report.

Andy.

**Comment by loodakrawa** [comment]
No worries - better safe than sorry :)

**Pull request merged**
